name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Maven + Java 21)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vitalmas-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build & test
        run: mvn -B -DskipTests=false clean verify

  frontend:
    name: Frontend (Vite)
    if: ${{ hashFiles('vitalmas-frontend/package.json') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vitalmas-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: vitalmas-frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
